In [3]:
import pandas as pd
import numpy as np
df1 = pd.read_csv("Advertising.csv",index_col=0)
df1

TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [12]:
perchan = df1.iloc[:,:-1].values
Sales = df1.iloc[:,-1].values


In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(perchan,Sales,test_size=0.3,random_state=0)


In [14]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(perchan,Sales)


LinearRegression()

In [23]:
Sales_pred = model.predict(x_test)

In [24]:
Sales_pred

array([ 9.95168206,  7.39497997,  7.10850249, 24.11860723, 12.1620464 ,
        6.55467   , 12.47834763, 15.29422368, 10.57712073, 16.3600003 ,
       22.89067208,  9.12734958, 10.5871997 , 15.50161696, 11.44592364,
       12.12295317, 18.86426829, 10.4276871 , 15.62347779, 17.32931197,
       24.13310013,  9.70853872, 15.16152314, 12.39914823,  5.74215558,
       15.0827909 , 12.38455495, 20.80301059, 13.6264571 ,  8.88787996,
       12.82365674, 21.2926106 , 18.36720534, 21.14027498,  6.4891503 ,
        6.05162411,  7.88410649, 13.18867186, 14.42184212,  6.12602215,
       11.8368039 ,  9.01603163, 14.98951429, 16.40377623, 17.1861428 ,
       13.21069202,  3.72734086, 11.85832174, 15.56609348,  8.76480262,
       10.62693815, 19.45441306, 18.53852096, 15.33707782,  9.8272711 ,
        8.14651887, 21.6339338 , 14.21383298, 16.37766467,  8.52771254])

In [22]:
y_test

array([11.3,  8.4,  8.7, 25.4, 11.7,  8.7,  7.2, 13.2,  9.2, 16.6, 24.2,
       10.6, 10.5, 15.6, 11.8, 13.2, 17.4,  1.6, 14.7, 17. , 26.2, 10.3,
       14.9, 12.9,  8.1, 15.2, 12.6, 22.6, 11.6,  8.5, 12.5, 23.7, 16.1,
       21.8,  5.6,  6.7,  9.7, 12.9, 13.6,  7.2, 10.8,  9.5, 15. , 15.9,
       17.1, 14. ,  4.8,  8.7, 15.9, 10.4, 12.4, 19.7, 17.6, 15.5, 10.1,
        9.7, 21.4, 14.4, 16.6,  5.5])

In [25]:
model.intercept_

2.9388893694594085

In [26]:
model.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [27]:
import statsmodels.formula.api as sm
#ordinary least square
modelAllin = sm.ols("Sales ~ TV + Radio +Newspaper",df1).fit()


In [28]:
modelAllin.params

Intercept    2.938889
TV           0.045765
Radio        0.188530
Newspaper   -0.001037
dtype: float64

In [29]:
y_mean = np.mean(df1.Sales)
mean_sum_square = np.sum((y_mean - df1.Sales)**2)


In [30]:
y_pred = modelAllin.predict(df1)

fit_sum_square = np.sum((y_pred - df1.Sales) **2)


In [32]:
p = 3
n = 200

F = (mean_sum_square-fit_sum_square)/p/ ((fit_sum_square)/(n-p-1))
F

570.2707036590942

In [ ]:
# ssfit 平方差越小越好 R平方 判斷係數 接近1月好 t統計 月高越好 p value (1 - 信心指數)
# forward selecting backward selecting mix
#feature selectind
import statsmodels.formula.api as sm
def get_par